name: Continuous Integration

on:
  pull_request:
    branches:
      -master
      -staging
  push:
    branches:
      -master
      -staging
      -setup_cypress_tests_for_flow_playground
env:
  PLAYGROUND_API: ''
  AVATAAR_URL: ''
  GA_TRACKING_CODE: ''
  MIXPANEL_TOKEN: ''
  DEFAULT_SEO_IMAGE: ''
  SENTRY_DSN: ''

jobs:
  test:
    name: 'Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: make ci

  cypress-e2e:
    name: Cypress Emulator Tests for Flow-Playground
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome103-ff102
    steps:
      - name: Spin up Docker Container
        uses: cypress-io/github-action@v4
        with:
          start: npm run start-docker
          wait-on: http://localhost:3000
          spec: cypress/e2e/playground.cy.js
          record: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
