name: Continuous Integration

on:
  pull_request:
    branches:
      -master
      -staging
  push:
    branches:
      -master
      -staging
      -setup_cypress_tests_for_flow_playground
env:
  PLAYGROUND_API: ''
  AVATAAR_URL: ''
  GA_TRACKING_CODE: ''
  MIXPANEL_TOKEN: ''
  DEFAULT_SEO_IMAGE: ''
  SENTRY_DSN: ''

jobs:
  test:
    name: 'Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: make ci

  cypress-e2e:
    name: Cypress Emulator Tests for Flow-Playground
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome103-ff102
    steps:
      - name: Spin up Docker Container
        run: 
